### ISSUE TITLE
[feature request] remove unneeded entries from Ore Tiers Book

### ISSUE THREAD

**Issue by Zygus42** [GlobbyPotato/Rockhounding_OreTiers#5]
rockhounding_oretiers-1.12.2-3.02

I set Magnetite to not spawn, as it is ore-dictionaried with the Magnetite from Futurepack, and I don't want there to be that much of it.  Would be great if that removed the entry from the Ore Tiers Book so that players don't go mining for something that doesn't exist.  

I would also like to extend the spawn range of one of the other types of iron ore to cover the gap left by the missing Magnetite, but that's another issue.

**Comment by GlobbyPotato** [comment]
Fixing the book is doable, I can fit the book entries to the worldgen enabler. Though, being the book written when created you need to craft another one to eventually see the changes.

For the magnetite part, it's not so easy because in the overworld tier ores are meant to generate in fixed biomes, locations and strata. Messing with the other ones to cover the gaps will either overpopulate the world of iron and kill the mod concept itself. If the oredict allows both magnetite to be treated the same in Futurpack you can try balance the two types, or inject with a ore generation mod something else in the lower strata.
